// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// guo_hall_cpp
IntegerMatrix guo_hall_cpp(IntegerMatrix img, int max_iter);
RcppExport SEXP _thinr_guo_hall_cpp(SEXP imgSEXP, SEXP max_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type img(imgSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(guo_hall_cpp(img, max_iter));
    return rcpp_result_gen;
END_RCPP
}
// k3m_cpp
IntegerMatrix k3m_cpp(IntegerMatrix img, int max_iter);
RcppExport SEXP _thinr_k3m_cpp(SEXP imgSEXP, SEXP max_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type img(imgSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(k3m_cpp(img, max_iter));
    return rcpp_result_gen;
END_RCPP
}
// lee_cpp
IntegerMatrix lee_cpp(IntegerMatrix img, int max_iter);
RcppExport SEXP _thinr_lee_cpp(SEXP imgSEXP, SEXP max_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type img(imgSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(lee_cpp(img, max_iter));
    return rcpp_result_gen;
END_RCPP
}
// zhang_suen_cpp
IntegerMatrix zhang_suen_cpp(IntegerMatrix img, int max_iter);
RcppExport SEXP _thinr_zhang_suen_cpp(SEXP imgSEXP, SEXP max_iterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type img(imgSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    rcpp_result_gen = Rcpp::wrap(zhang_suen_cpp(img, max_iter));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_thinr_guo_hall_cpp", (DL_FUNC) &_thinr_guo_hall_cpp, 2},
    {"_thinr_k3m_cpp", (DL_FUNC) &_thinr_k3m_cpp, 2},
    {"_thinr_lee_cpp", (DL_FUNC) &_thinr_lee_cpp, 2},
    {"_thinr_zhang_suen_cpp", (DL_FUNC) &_thinr_zhang_suen_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_thinr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
