# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.guo_hall_cpp <- function(img, max_iter) {
    .Call(`_thinr_guo_hall_cpp`, img, max_iter)
}

.k3m_cpp <- function(img, max_iter) {
    .Call(`_thinr_k3m_cpp`, img, max_iter)
}

.lee_cpp <- function(img, max_iter) {
    .Call(`_thinr_lee_cpp`, img, max_iter)
}

.zhang_suen_cpp <- function(img, max_iter) {
    .Call(`_thinr_zhang_suen_cpp`, img, max_iter)
}

