# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.distance_transform_cpp <- function(img, metric) {
    .Call(`_thinr_distance_transform_cpp`, img, metric)
}

.guo_hall_cpp <- function(img, max_iter) {
    .Call(`_thinr_guo_hall_cpp`, img, max_iter)
}

.hilditch_cpp <- function(img, max_iter) {
    .Call(`_thinr_hilditch_cpp`, img, max_iter)
}

.holt_cpp <- function(img, max_iter) {
    .Call(`_thinr_holt_cpp`, img, max_iter)
}

.k3m_cpp <- function(img, max_iter) {
    .Call(`_thinr_k3m_cpp`, img, max_iter)
}

.lee_cpp <- function(img, max_iter) {
    .Call(`_thinr_lee_cpp`, img, max_iter)
}

.medial_axis_cpp <- function(img) {
    .Call(`_thinr_medial_axis_cpp`, img)
}

.opta_cpp <- function(img, max_iter) {
    .Call(`_thinr_opta_cpp`, img, max_iter)
}

.pavlidis_cpp <- function(img, max_iter) {
    .Call(`_thinr_pavlidis_cpp`, img, max_iter)
}

.stentiford_cpp <- function(img, max_iter) {
    .Call(`_thinr_stentiford_cpp`, img, max_iter)
}

.zhang_suen_cpp <- function(img, max_iter) {
    .Call(`_thinr_zhang_suen_cpp`, img, max_iter)
}

